# Generated by Django 3.1.2 on 2020-10-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201027_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='field',
            field=models.CharField(max_length=2),
        ),
    ]
